import { Suspense } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { getBudgetInsights, type BudgetInsightsInput } from '@/ai/flows/budget-insights-from-transactions';
import { Skeleton } from '@/components/ui/skeleton';
import { AlertTriangle, Lightbulb } from 'lucide-react';

async function BudgetInsights() {
  // Mock data for demonstration purposes
  const mockInput: BudgetInsightsInput = {
    project_id: 'proj_123',
    budget_limit: 50000,
    transactions: [
      { id: 'txn_1', project_id: 'proj_123', type: 'expense', amount: 15000, category: 'Materials', timestamp: new Date().toISOString() },
      { id: 'txn_2', project_id: 'proj_123', type: 'expense', amount: 25000, category: 'Labor', timestamp: new Date().toISOString() },
      { id: 'txn_3', project_id: 'proj_123', type: 'expense', amount: 7000, category: 'Equipment Rental', timestamp: new Date().toISOString() },
      { id: 'txn_4', project_id: 'proj_123', type: 'income', amount: 10000, category: 'Client Payment', timestamp: new Date().toISOString() },
      { id: 'txn_5', project_id: 'proj_123', type: 'expense', amount: 5000, category: 'Permits', timestamp: new Date().toISOString() },
    ],
  };

  try {
    const insights = await getBudgetInsights(mockInput);
    return (
        <div className="prose prose-sm max-w-none text-card-foreground">
            <p>{insights.summary}</p>
        </div>
    );
  } catch (error) {
    return (
        <div className="flex items-center gap-4 text-destructive">
            <AlertTriangle className="h-8 w-8" />
            <div>
                <p className="font-semibold">Failed to generate insights.</p>
                <p className="text-sm">The AI service may be temporarily unavailable. Please try again later.</p>
            </div>
        </div>
    );
  }
}

function BudgetInsightsSkeleton() {
    return (
        <div className="space-y-3">
            <Skeleton className="h-4 w-full" />
            <Skeleton className="h-4 w-full" />
            <Skeleton className="h-4 w-3/4" />
        </div>
    );
}

export default function BudgetPage() {
  return (
    <>
      <div className="flex items-center">
        <h1 className="text-lg font-semibold md:text-2xl font-headline">AI Budget Overview</h1>
      </div>
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Lightbulb className="h-5 w-5 text-accent"/>
            AI-Powered Analysis
          </CardTitle>
          <CardDescription>
            This summary is generated by AI based on recent project transactions. It highlights potential financial risks and spending patterns.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Suspense fallback={<BudgetInsightsSkeleton />}>
            <BudgetInsights />
          </Suspense>
        </CardContent>
      </Card>
    </>
  );
}
